### PR TITLE
Support Architectury API

### PR DESCRIPTION
**Pull request by ZekerZhayard**
Only tested with Architectury API for 1.18.1 and 1.18.2, may crash in 1.17.1 or 1.16.5

### CODE REVIEW

**Comment by ghost** [comment]
Looks good. Seems to work fine too. GG Sir, you basically took all this on yourself.

**Comment by ghost** [comment]
Seems to be an issue with your update, When trying to type in the console for commands, game crashes with following error: Caused by: java.lang.invoke.LambdaConversionException: Type mismatch in captured lambda parameter 0: expecting class net.minecraft.class_437, found interface net.minecraft.class_364

**Comment by ZekerZhayard** [comment]
@MrFawkes1337 ohhhhh thanks for reporting! i'll fix it

**Comment by ZekerZhayard** [comment]
@MrFawkes1337 fixed,
[optifabric-1.12.10.jar.zip](https://github.com/lordofpipes/OptiFabric/files/8324807/optifabric-1.12.10.jar.zip)

**Comment by ghost** [comment]
Beautiful! I only found it by accident, Glad I could help! :D

**Pull request merged**
